export interface Content {
  nav: {
    avaleht: string
    minust: string
    teenused: string
    kkk: string
    kontakt: string
  }
  footer: {
    copy: string
  }
  avaleht: {
    hero_subtitle: string
    hero_h1: string
    hero_text: string
    hero_btn_primary: string
    hero_btn_outline: string
    intro_label: string
    intro_h2: string
    intro_text: string
    intro_btn: string
    services_label: string
    services_h2: string
    services_text: string
    card1_h3: string
    card1_text: string
    card2_h3: string
    card2_text: string
    card3_h3: string
    card3_text: string
    cards_btn: string
    quote: string
    cta_h2: string
    cta_text: string
    cta_btn: string
  }
  minust: {
    page_label: string
    page_h1: string
    about_label: string
    about_h2: string
    about_p1: string
    about_p2: string
    about_p3: string
    values_label: string
    values_h2: string
    value1_h3: string
    value1_text: string
    value2_h3: string
    value2_text: string
    value3_h3: string
    value3_text: string
    value4_h3: string
    value4_text: string
    edu_label: string
    edu_h2: string
    edu1_year: string
    edu1_title: string
    edu1_text: string
    edu2_year: string
    edu2_title: string
    edu2_text: string
    edu3_year: string
    edu3_title: string
    edu3_text: string
    edu4_year: string
    edu4_title: string
    edu4_text: string
    cta_h2: string
    cta_text: string
    cta_btn1: string
    cta_btn2: string
  }
  teenused: {
    page_label: string
    page_h1: string
    services_label: string
    services_h2: string
    services_text: string
    s1_label: string
    s1_h3: string
    s1_text: string
    s1_li1: string
    s1_li2: string
    s1_li3: string
    s1_li4: string
    s2_label: string
    s2_h3: string
    s2_text: string
    s2_li1: string
    s2_li2: string
    s2_li3: string
    s2_li4: string
    s3_label: string
    s3_h3: string
    s3_text: string
    s3_li1: string
    s3_li2: string
    s3_li3: string
    s3_li4: string
    prices_label: string
    prices_h2: string
    prices_text: string
    p1_title: string
    p1_r1_name: string
    p1_r1_price: string
    p1_r2_name: string
    p1_r2_price: string
    p1_r3_name: string
    p1_r3_price: string
    p1_r4_name: string
    p1_r4_price: string
    p1_r5_name: string
    p1_r5_price: string
    p2_badge: string
    p2_title: string
    p2_r1_name: string
    p2_r1_price: string
    p2_r2_name: string
    p2_r2_price: string
    p2_r3_name: string
    p2_r3_price: string
    p2_r4_name: string
    p2_r4_price: string
    p2_r5_name: string
    p2_r5_price: string
    p3_title: string
    p3_r1_name: string
    p3_r1_price: string
    p3_r2_name: string
    p3_r2_price: string
    p3_r3_name: string
    p3_r3_price: string
    p3_r4_name: string
    p3_r4_price: string
    prices_note: string
    cta_h2: string
    cta_text: string
    cta_btn: string
  }
  kkk: {
    page_label: string
    page_h1: string
    g1_title: string
    g1_q1: string
    g1_a1: string
    g1_q2: string
    g1_a2: string
    g1_q3: string
    g1_a3: string
    g1_q4: string
    g1_a4: string
    g2_title: string
    g2_q1: string
    g2_a1: string
    g2_q2: string
    g2_a2: string
    g2_q3: string
    g2_a3: string
    g2_q4: string
    g2_a4: string
    g3_title: string
    g3_q1: string
    g3_a1: string
    g3_q2: string
    g3_a2: string
    g3_q3: string
    g3_a3: string
    cta_h2: string
    cta_text: string
    cta_btn: string
  }
  kontakt: {
    page_label: string
    page_h1: string
    form_h2: string
    form_text: string
    form_success: string
    form_btn: string
    info_h2: string
    info_email_label: string
    info_email: string
    info_phone_label: string
    info_phone: string
    info_location_label: string
    info_location: string
    info_location_note: string
    info_hours_label: string
    info_hours: string
    info_social_label: string
    info_instagram_url: string
    info_facebook_url: string
  }
}
